# Generated by Django 5.1.6 on 2026-09-22 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublishLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("action", models.CharField(max_length=32, verbose_name="动作")),
                (
                    "payload",
                    models.JSONField(blank=True, default=dict, verbose_name="请求负载"),
                ),
                (
                    "response",
                    models.JSONField(blank=True, default=dict, verbose_name="响应内容"),
                ),
                (
                    "status_code",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="HTTP 状态码"
                    ),
                ),
                (
                    "message",
                    models.TextField(blank=True, default="", verbose_name="消息"),
                ),
                (
                    "duration_ms",
                    models.PositiveIntegerField(default=0, verbose_name="耗时 ms"),
                ),
            ],
            options={
                "verbose_name": "发布日志",
                "verbose_name_plural": "发布日志",
                "db_table": "publish_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PublishTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="是否删除"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="删除时间"
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("wechat", "公众号"),
                            ("xiaohongshu", "小红书"),
                            ("douyin", "抖音"),
                            ("zhihu", "知乎"),
                            ("weibo", "微博"),
                            ("bilibili", "B站"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="平台",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待发布"),
                            ("publishing", "发布中"),
                            ("success", "成功"),
                            ("failed", "失败"),
                            ("canceled", "已取消"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "scheduled_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="计划发布时间",
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="实际发布时间"
                    ),
                ),
                (
                    "platform_content_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=128,
                        verbose_name="平台内容ID",
                    ),
                ),
                (
                    "error_msg",
                    models.TextField(blank=True, default="", verbose_name="错误信息"),
                ),
                (
                    "retry_count",
                    models.PositiveIntegerField(default=0, verbose_name="重试次数"),
                ),
                (
                    "max_retries",
                    models.PositiveIntegerField(default=3, verbose_name="最大重试"),
                ),
                (
                    "payload",
                    models.JSONField(blank=True, default=dict, verbose_name="发布负载"),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="publish_tasks",
                        to="accounts.account",
                        verbose_name="账号",
                    ),
                ),
            ],
            options={
                "verbose_name": "发布任务",
                "verbose_name_plural": "发布任务",
                "db_table": "publish_tasks",
                "ordering": ["-created_at"],
            },
        ),
    ]
