# Generated by Django 5.1.6 on 2026-09-22 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("content", "0002_initial"),
        ("publish", "0001_initial"),
        ("teams", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="publishtask",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_publish_tasks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建人",
            ),
        ),
        migrations.AddField(
            model_name="publishtask",
            name="draft",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="publish_tasks",
                to="content.contentdraft",
                verbose_name="草稿",
            ),
        ),
        migrations.AddField(
            model_name="publishtask",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="teams.team",
                verbose_name="所属团队",
            ),
        ),
        migrations.AddField(
            model_name="publishlog",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="logs",
                to="publish.publishtask",
                verbose_name="任务",
            ),
        ),
        migrations.AddIndex(
            model_name="publishtask",
            index=models.Index(
                fields=["team", "status"], name="publish_tas_team_id_6dd8d3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="publishtask",
            index=models.Index(
                fields=["account", "status"], name="publish_tas_account_c0c3f9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="publishtask",
            index=models.Index(
                fields=["scheduled_at", "status"], name="publish_tas_schedul_4b97b8_idx"
            ),
        ),
    ]
