# Generated by Django 5.1.6 on 2026-09-22 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Invitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="被邀邮箱")),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "管理员"),
                            ("editor", "编辑"),
                            ("reviewer", "审核员"),
                            ("viewer", "只读"),
                        ],
                        default="viewer",
                        max_length=20,
                        verbose_name="拟授角色",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        db_index=True,
                        max_length=64,
                        unique=True,
                        verbose_name="邀请 token",
                    ),
                ),
                ("expires_at", models.DateTimeField(verbose_name="过期时间")),
                (
                    "accepted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="接受时间"
                    ),
                ),
            ],
            options={
                "verbose_name": "邀请",
                "verbose_name_plural": "邀请",
                "db_table": "team_invitations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="是否删除"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="删除时间"
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="团队名")),
                ("avatar", models.URLField(blank=True, verbose_name="团队头像")),
                ("description", models.TextField(blank=True, verbose_name="简介")),
            ],
            options={
                "verbose_name": "团队",
                "verbose_name_plural": "团队",
                "db_table": "teams",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "管理员"),
                            ("editor", "编辑"),
                            ("reviewer", "审核员"),
                            ("viewer", "只读"),
                        ],
                        default="viewer",
                        max_length=20,
                        verbose_name="角色",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待接受"),
                            ("active", "已加入"),
                            ("disabled", "已禁用"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "joined_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="加入时间"
                    ),
                ),
            ],
            options={
                "verbose_name": "团队成员",
                "verbose_name_plural": "团队成员",
                "db_table": "team_members",
            },
        ),
    ]
