# Generated by Django 5.1.6 on 2026-09-23 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="plan",
            field=models.CharField(
                choices=[
                    ("free", "免费版"),
                    ("personal", "个人版"),
                    ("team", "团队版"),
                    ("enterprise", "企业版"),
                ],
                default="free",
                max_length=20,
                verbose_name="套餐",
            ),
        ),
    ]
