# Generated by Django 5.1.6 on 2026-09-22 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="是否删除"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="删除时间"
                    ),
                ),
                ("date", models.DateField(db_index=True, verbose_name="数据日期")),
                ("views", models.BigIntegerField(default=0, verbose_name="阅读")),
                ("likes", models.BigIntegerField(default=0, verbose_name="点赞")),
                ("comments", models.BigIntegerField(default=0, verbose_name="评论")),
                ("shares", models.BigIntegerField(default=0, verbose_name="转发")),
                ("followers", models.BigIntegerField(default=0, verbose_name="粉丝数")),
                (
                    "follower_growth",
                    models.BigIntegerField(default=0, verbose_name="新增粉丝"),
                ),
                (
                    "raw",
                    models.JSONField(blank=True, default=dict, verbose_name="原始数据"),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stats",
                        to="accounts.account",
                        verbose_name="账号",
                    ),
                ),
            ],
            options={
                "verbose_name": "平台数据快照",
                "verbose_name_plural": "平台数据快照",
                "db_table": "dashboard_platform_stats",
                "ordering": ["-date"],
            },
        ),
    ]
