# Generated by Django 5.1.6 on 2026-09-22 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dashboard", "0001_initial"),
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="platformstats",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="teams.team",
                verbose_name="所属团队",
            ),
        ),
        migrations.AddIndex(
            model_name="platformstats",
            index=models.Index(
                fields=["team", "date"], name="dashboard_p_team_id_68a9e7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="platformstats",
            index=models.Index(
                fields=["account", "date"], name="dashboard_p_account_98a9b0_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="platformstats",
            constraint=models.UniqueConstraint(
                fields=("account", "date"), name="uniq_account_date"
            ),
        ),
    ]
