# Generated by Django 5.1.6 on 2026-09-22 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContentDraft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="是否删除"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="删除时间"
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="标题")),
                (
                    "content_md",
                    models.TextField(
                        blank=True, default="", verbose_name="Markdown 正文"
                    ),
                ),
                (
                    "cover_url",
                    models.URLField(blank=True, default="", verbose_name="封面 URL"),
                ),
                (
                    "tags",
                    models.JSONField(blank=True, default=list, verbose_name="标签"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("pending", "待审"),
                            ("published", "已发布"),
                            ("failed", "失败"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "version_no",
                    models.PositiveIntegerField(default=1, verbose_name="当前版本号"),
                ),
                (
                    "platforms",
                    models.JSONField(blank=True, default=list, verbose_name="目标平台"),
                ),
            ],
            options={
                "verbose_name": "内容草稿",
                "verbose_name_plural": "内容草稿",
                "db_table": "content_drafts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContentVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "version_no",
                    models.PositiveIntegerField(db_index=True, verbose_name="版本号"),
                ),
                ("title", models.CharField(max_length=200, verbose_name="标题")),
                (
                    "content_md",
                    models.TextField(
                        blank=True, default="", verbose_name="Markdown 正文"
                    ),
                ),
                (
                    "cover_url",
                    models.URLField(blank=True, default="", verbose_name="封面 URL"),
                ),
                (
                    "tags",
                    models.JSONField(blank=True, default=list, verbose_name="标签"),
                ),
                (
                    "platforms",
                    models.JSONField(blank=True, default=list, verbose_name="目标平台"),
                ),
                (
                    "changelog",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="变更说明"
                    ),
                ),
            ],
            options={
                "verbose_name": "内容版本",
                "verbose_name_plural": "内容版本",
                "db_table": "content_versions",
                "ordering": ["-version_no"],
            },
        ),
    ]
