# Generated by Django 5.1.6 on 2026-09-22 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "action",
                    models.CharField(db_index=True, max_length=32, verbose_name="动作"),
                ),
                (
                    "resource",
                    models.CharField(db_index=True, max_length=64, verbose_name="资源"),
                ),
                (
                    "resource_id",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="资源ID"
                    ),
                ),
                (
                    "ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP"
                    ),
                ),
                ("ua", models.TextField(blank=True, default="", verbose_name="UA")),
                (
                    "payload",
                    models.JSONField(blank=True, default=dict, verbose_name="操作负载"),
                ),
                (
                    "status_code",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="HTTP 状态码"
                    ),
                ),
                (
                    "request_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=64,
                        verbose_name="请求ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "操作日志",
                "verbose_name_plural": "操作日志",
                "db_table": "audit_logs",
                "ordering": ["-created_at"],
            },
        ),
    ]
