# Generated by Django 5.1.6 on 2026-09-22 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AIGeneration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="是否删除"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="删除时间"
                    ),
                ),
                ("action", models.CharField(max_length=20, verbose_name="动作")),
                (
                    "prompt",
                    models.TextField(
                        blank=True, default="", verbose_name="输入 prompt"
                    ),
                ),
                (
                    "params",
                    models.JSONField(blank=True, default=dict, verbose_name="参数"),
                ),
                (
                    "output",
                    models.TextField(blank=True, default="", verbose_name="生成结果"),
                ),
                (
                    "model",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="模型"
                    ),
                ),
                (
                    "tokens_input",
                    models.PositiveIntegerField(default=0, verbose_name="输入 tokens"),
                ),
                (
                    "tokens_output",
                    models.PositiveIntegerField(default=0, verbose_name="输出 tokens"),
                ),
                (
                    "duration_ms",
                    models.PositiveIntegerField(default=0, verbose_name="耗时 ms"),
                ),
                (
                    "platform",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("wechat", "公众号"),
                            ("xiaohongshu", "小红书"),
                            ("douyin", "抖音"),
                            ("zhihu", "知乎"),
                            ("weibo", "微博"),
                            ("bilibili", "B站"),
                        ],
                        default="",
                        max_length=20,
                        verbose_name="目标平台",
                    ),
                ),
                ("success", models.BooleanField(default=True, verbose_name="是否成功")),
                (
                    "error",
                    models.TextField(blank=True, default="", verbose_name="错误信息"),
                ),
            ],
            options={
                "verbose_name": "AI 生成记录",
                "verbose_name_plural": "AI 生成记录",
                "db_table": "ai_generations",
                "ordering": ["-created_at"],
            },
        ),
    ]
