# Generated by Django 5.1.6 on 2026-09-22 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ai", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="aigeneration",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ai_generations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="调用者",
            ),
        ),
        migrations.AddIndex(
            model_name="aigeneration",
            index=models.Index(
                fields=["team", "action"], name="ai_generati_team_id_81ebd6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aigeneration",
            index=models.Index(
                fields=["user", "created_at"], name="ai_generati_user_id_a0b927_idx"
            ),
        ),
    ]
