# Generated by Django 5.1.6 on 2026-09-22 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="是否删除"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="删除时间"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("image", "图片"),
                            ("video", "视频"),
                            ("audio", "音频"),
                            ("document", "文档"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="类型",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="素材名")),
                (
                    "object_key",
                    models.CharField(
                        db_index=True, max_length=512, verbose_name="MinIO key"
                    ),
                ),
                (
                    "url",
                    models.URLField(blank=True, default="", verbose_name="可访问 URL"),
                ),
                ("size", models.BigIntegerField(default=0, verbose_name="大小(bytes)")),
                (
                    "content_type",
                    models.CharField(
                        blank=True, default="", max_length=128, verbose_name="MIME 类型"
                    ),
                ),
                (
                    "hash_sha256",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=64,
                        verbose_name="SHA256",
                    ),
                ),
                (
                    "tags",
                    models.JSONField(blank=True, default=list, verbose_name="标签"),
                ),
                (
                    "meta",
                    models.JSONField(blank=True, default=dict, verbose_name="元数据"),
                ),
            ],
            options={
                "verbose_name": "素材",
                "verbose_name_plural": "素材",
                "db_table": "materials",
                "ordering": ["-created_at"],
            },
        ),
    ]
