# Generated by Django 5.1.6 on 2026-09-22 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("materials", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="uploader",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="materials",
                to=settings.AUTH_USER_MODEL,
                verbose_name="上传者",
            ),
        ),
        migrations.AddIndex(
            model_name="material",
            index=models.Index(
                fields=["team", "type"], name="materials_team_id_7d1658_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="material",
            index=models.Index(
                fields=["team", "hash_sha256"], name="materials_team_id_324bed_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="material",
            index=models.Index(
                fields=["uploader", "created_at"], name="materials_uploade_c18a32_idx"
            ),
        ),
    ]
