# Generated by Django 5.1.6 on 2026-09-23 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="material",
            name="url",
            field=models.URLField(
                blank=True, default="", max_length=1024, verbose_name="稳定访问路径"
            ),
        ),
    ]
