# Generated by Django 5.1.6 on 2026-09-22 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="是否删除"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="删除时间"
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("wechat", "公众号"),
                            ("xiaohongshu", "小红书"),
                            ("douyin", "抖音"),
                            ("zhihu", "知乎"),
                            ("weibo", "微博"),
                            ("bilibili", "B站"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="平台",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="账号昵称")),
                ("avatar", models.URLField(blank=True, verbose_name="头像")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "正常"),
                            ("expired", "已过期"),
                            ("error", "异常"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("followers", models.BigIntegerField(default=0, verbose_name="粉丝数")),
                (
                    "account_group",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="账号分组"
                    ),
                ),
                (
                    "platform_account_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=128,
                        verbose_name="平台账号ID",
                    ),
                ),
                (
                    "encrypted_token",
                    models.TextField(blank=True, default="", verbose_name="加密 Token"),
                ),
                (
                    "token_expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Token 过期时间"
                    ),
                ),
                (
                    "last_synced_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最后同步时间"
                    ),
                ),
                (
                    "raw_extra",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="平台原始字段"
                    ),
                ),
            ],
            options={
                "verbose_name": "平台账号",
                "verbose_name_plural": "平台账号",
                "db_table": "accounts",
                "ordering": ["-created_at"],
            },
        ),
    ]
