# Generated by Django 5.1.6 on 2026-09-22 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("teams", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="added_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="added_accounts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="绑定人",
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="teams.team",
                verbose_name="所属团队",
            ),
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(
                fields=["team", "platform"], name="accounts_team_id_09c0f8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(
                fields=["team", "status"], name="accounts_team_id_ab5984_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(
                fields=["platform", "status"], name="accounts_platfor_ce557b_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="account",
            constraint=models.UniqueConstraint(
                fields=("team", "platform", "platform_account_id"),
                name="uniq_team_platform_account",
            ),
        ),
    ]
