# Generated by Django 5.1.6 on 2026-09-22 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReviewRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("submit", "提交"),
                            ("approve", "通过"),
                            ("reject", "驳回"),
                            ("rollback", "回滚"),
                        ],
                        max_length=20,
                        verbose_name="动作",
                    ),
                ),
                ("stage", models.CharField(max_length=32, verbose_name="阶段")),
                (
                    "comment",
                    models.TextField(blank=True, default="", verbose_name="审核意见"),
                ),
            ],
            options={
                "verbose_name": "审核记录",
                "verbose_name_plural": "审核记录",
                "db_table": "review_records",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReviewFlow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="是否删除"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="删除时间"
                    ),
                ),
                (
                    "current_stage",
                    models.CharField(
                        default="submit", max_length=32, verbose_name="当前阶段"
                    ),
                ),
                (
                    "config",
                    models.JSONField(blank=True, default=dict, verbose_name="审核配置"),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="提交时间"
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最终通过时间"
                    ),
                ),
                (
                    "draft",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_flow",
                        to="content.contentdraft",
                        verbose_name="草稿",
                    ),
                ),
            ],
            options={
                "verbose_name": "审核流程",
                "verbose_name_plural": "审核流程",
                "db_table": "review_flows",
                "ordering": ["-created_at"],
            },
        ),
    ]
