# Generated by Django 5.1.6 on 2026-09-22 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("reviews", "0001_initial"),
        ("teams", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="reviewflow",
            name="submitted_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="submitted_review_flows",
                to=settings.AUTH_USER_MODEL,
                verbose_name="提交人",
            ),
        ),
        migrations.AddField(
            model_name="reviewflow",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="teams.team",
                verbose_name="所属团队",
            ),
        ),
        migrations.AddField(
            model_name="reviewrecord",
            name="flow",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="records",
                to="reviews.reviewflow",
                verbose_name="流程",
            ),
        ),
        migrations.AddField(
            model_name="reviewrecord",
            name="reviewer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="review_records",
                to=settings.AUTH_USER_MODEL,
                verbose_name="审核人",
            ),
        ),
    ]
